server:
  port: 10180
  servlet:
    context-path: /sirbee

#上传图片  服务器的地址   端口   账号  密码
img.path: /opt/pictures/
img.server.address: 67.209.188.215
img.server.port: 29014
img.server.username: root
img.server.password: 234561aA


#自定义   @Value("${配置文件中的参数名}")  redis://127.0.0.1:6379   172.25.241.232:26379,172.25.241.233:26379,172.25.241.234:26379
#qpsafety.sso.redis.address: redis://172.25.241.232:26379,redis://172.25.241.233:26379,redis://172.25.241.234:26379
#qpsafety.sso.redis.expire.minite: 1440

#qpsafety.sso.server: localhost:10174/qpsafety-sso/
#qpsafety.sso.logout.path: /logout
#qpsafety.sso.excluded.paths: /unlogin/**,/app/**,

#xst.insertLogger.address: http://172.25.241.235:10176/work_order_system/pc/insertLog
#青浦平安
#xst.insertLogger.address: http://192.168.128.116:10176/work_order_system/pc/insertLog
#新凌空云测试
#xst.insertLogger.address: http://172.25.241.238:10176/work_order_system/pc/insertLog




### xxl-sso
#xxl.sso.server=http://qpsafety.com:10174/qpsafety-sso/
#xxl.sso.logout.path=/logout
#xxl-sso.excluded.paths=/pc/**,/app/**




#spring
spring:
  mvc:
    static-path-pattern: /static/**





#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  datasource:
    druid:
  # 数据库访问配置, 使用druid数据源
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver

      url: jdbc:mysql://localhost:3306/sirbee?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 234561aA

#los angeles
#      url: jdbc:mysql://67.209.188.215:3306/sirbee?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
#      username: root
#      password: 234561aA

      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 100
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat
      # Spring监控AOP切入点，如 x.y.z.service.*,配置多个英文逗号分隔   cc.mrbird.*.servie.*
      aop-patterns: com.chinaunicom.sirbee.service.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  resources:
    static-locations: classpath:/static/
  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册












  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    request-context-attribute: request

#172.25.241.232:26379,172.25.241.233:26379,172.25.241.234:26379    主从
  redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
#      host: 127.0.0.1
      # Redis服务器连接端口
#      port: 6379
      # Redis 密码
      jedis:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 8
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 2000
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 10000
      # 连接超时时间（毫秒）
      timeout: 0
      password:
#      cluster:
#        nodes: 172.25.241.232:26379,172.25.241.233:26379,172.25.241.234:26379
      sentinel:
        master: mymaster
#        这个线上服务器ping不通    下面这个是本地拼不通
#        nodes: 172.25.241.232:26379,172.25.241.233:26379,172.25.241.234:26379

#       青浦平安
        nodes: 192.168.128.101:26379,192.168.128.102:26379,192.168.128.103:26379


#        nodes: 10.0.50.121:26379,10.0.50.122:26379,10.0.50.123:26379

#新的凌空云测试服务器
#        nodes: 172.25.241.229:26379,172.25.241.230:26379,172.25.241.231:26379





mybatis:
  # type-aliases扫描路径  cc.mrbird.system.domain,cc.mrbird.job.domain
  type-aliases-package: com.chinaunicom.sirbee.dao.model
  # mapper xml实现扫描路径    这个xml 放在resource中  放在java中不行  打包不成功
  mapper-locations: classpath:xml/*.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true



#这个不用  直接application中扫描mapper   @MapperScan("com.chinaunicom.sirbee.dao.mapper")
#mapper:
#  mappers: com.chinaunicom.sirbee.config.MyMapper
#  not-empty: false
#  identity: MYSQL


pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:log4j2.yml
#logging:
#  config: classpath:log4j2.yml







